-- 032_vuln_target_map.sql
-- Seed: npm packages with a disclosed CWE-22/78/918 history (GitHub Advisory
-- Database, gathered 2026-09-08). credential_score ranks reputation value;
-- pays is false across this set — npm OSS vuln disclosure is unpaid (verified:
-- budibase and n8n, the heaviest company-backed offenders, run no paid program).
-- This is a hunting/target inventory for future runs, not a payer list.

CREATE TABLE IF NOT EXISTS vuln_target_map (
  ecosystem TEXT NOT NULL DEFAULT 'npm',
  package TEXT NOT NULL,
  cwe_classes TEXT[] NOT NULL DEFAULT '{}',
  advisory_count INTEGER NOT NULL DEFAULT 0,
  worst_severity TEXT,
  credential_score NUMERIC(4,2) NOT NULL DEFAULT 0,
  pays BOOLEAN NOT NULL DEFAULT false,
  pays_via TEXT,
  company_backed BOOLEAN NOT NULL DEFAULT false,
  source TEXT NOT NULL DEFAULT 'ghsa',
  gathered_on DATE NOT NULL DEFAULT '2026-09-08',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (ecosystem, package)
);
CREATE INDEX IF NOT EXISTS idx_vuln_target_map_rank ON vuln_target_map(pays DESC, credential_score DESC);

INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','openclaw','{"CWE-918","CWE-22","CWE-78"}',28,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','n8n','{"CWE-918","CWE-22","CWE-78"}',11,'high',0.81,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','pnpm','{"CWE-22","CWE-78"}',10,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@budibase/server','{"CWE-22","CWE-918"}',10,'critical',0.9,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','ghost','{"CWE-918","CWE-22"}',7,'medium',0.67,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','nocodb','{"CWE-22","CWE-918"}',6,'medium',0.67,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','network-ai','{"CWE-22","CWE-78"}',5,'critical',0.9,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','axios','{"CWE-918"}',4,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','electerm','{"CWE-22","CWE-78"}',4,'critical',0.9,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','deepseek-tui','{"CWE-22","CWE-918"}',4,'critical',0.9,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','9router','{"CWE-918","CWE-78"}',4,'critical',0.9,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@asymmetric-effort/specifyjs','{"CWE-918"}',4,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','fast-uri','{"CWE-918","CWE-22"}',3,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','ip-address','{"CWE-918"}',3,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','mcp-searxng','{"CWE-918"}',3,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@evomap/evolver','{"CWE-22","CWE-78"}',3,'critical',0.9,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','postcss','{"CWE-22"}',3,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','sillytavern','{"CWE-22","CWE-918"}',3,'critical',0.9,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','n8n-mcp','{"CWE-22","CWE-918"}',3,'high',0.81,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','magicmirror','{"CWE-918"}',3,'critical',0.9,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','next','{"CWE-918"}',3,'high',0.81,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','ssrfcheck','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','tmp','{"CWE-22"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','swagger-typescript-api','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@aborruso/ckan-mcp-server','{"CWE-918"}',2,'medium',0.62,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@ooples/token-optimizer-mcp','{"CWE-22","CWE-78"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','i18next-http-middleware','{"CWE-22","CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@anthropic-ai/claude-code','{"CWE-22","CWE-78"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@angular/platform-server','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','aws-cdk-lib','{"CWE-78"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','electron','{"CWE-78","CWE-918"}',2,'medium',0.62,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','jsii-diff','{"CWE-78"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','systeminformation','{"CWE-78"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','shescape','{"CWE-78"}',2,'critical',0.85,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','praisonai','{"CWE-78"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@lobehub/lobehub','{"CWE-78","CWE-918"}',2,'critical',0.85,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@steipete/summarize','{"CWE-918"}',2,'medium',0.62,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@tak-ps/cloudtak','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','apostrophe','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','auth-fetch-mcp','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','budibase','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','link-preview-js','{"CWE-918"}',2,'high',0.76,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@haxtheweb/open-apis','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@better-auth/sso','{"CWE-918"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','open-websearch','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@google/gemini-cli','{"CWE-78"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','astro','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@apostrophecms/import-export','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@asymmetric-effort/nogginlessdom','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@fastify/static','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@hapi/inert','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@hono/node-server','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@humanfs/node','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@logto/tunnel','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@puchunjie/doc-tools-mcp','{"CWE-22"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@rhinostone/swig','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@samanhappy/mcphub','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@wakaru/cli','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','better-helperjs','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','boxlite','{"CWE-22"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','browse-mcp','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','browserstack-runner','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','dbgate','{"CWE-22"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','esbuild','{"CWE-22"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','extract-zip','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','hono','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','libreoffice-convert','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','n8n-nodes-sqlite3','{"CWE-22"}',1,'medium',0.57,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','nitro','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','obsidian-local-rest-api','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','shamefile','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','short-video-maker','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','sublinear-time-solver','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','thrift','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','whistle','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@babel/core','{"CWE-22"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','prompty','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','vite','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@strapi/strapi','{"CWE-22"}',1,'critical',0.8,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','mcp-ssh-tool','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','ep_etherpad-lite','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','mcp-memory-keeper','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@gitlawb/openclaude','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','decompress','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@bitbonsai/mcpvault','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@vitest/browser','{"CWE-22"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','chrome-devtools-mcp','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','nx','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@xhmikosr/decompress','{"CWE-22"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@angular/ssr','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','flowise-components','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','i18next-fs-backend','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','claude-faf-mcp','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','faf-mcp','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','grok-faf-mcp','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','i18next-http-backend','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','i18next-locize-backend','{"CWE-22"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@cardano402/mcp-server','{"CWE-22","CWE-918"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','orval','{"CWE-22","CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','vitest','{"CWE-22"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','kysely','{"CWE-22"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@budibase/backend-core','{"CWE-918"}',1,'high',0.71,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','nodemailer','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','dbgate-api','{"CWE-78"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','degit','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','shell-quote','{"CWE-78"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@apostrophecms/cli','{"CWE-78"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@cyclonedx/cyclonedx-npm','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@n8n/computer-use','{"CWE-78"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@nocobase/plugin-backups','{"CWE-78"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@profullstack/mcp-server','{"CWE-78"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@wdio/browserstack-service','{"CWE-78"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','agentic-flow','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','automagik-genie','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','gemini-mcp-tool','{"CWE-78"}',1,'critical',0.8,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','node-ts-ocr','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','protobufjs-cli','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','claude-code-templates','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@cyclonedx/cdxgen','{"CWE-78"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@grackle-ai/runtime-sdk','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','claude-code-cache-fix','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','openlearnx','{"CWE-78"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@apify/actors-mcp-server','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@astrojs/cloudflare','{"CWE-918"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@astrojs/netlify','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@contentful/mcp-server','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@dadigua/hyperchat','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@frontmcp/adapters','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@haxtheweb/haxcms-nodejs','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@jshookmcp/jshook','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@karakeep/sdk','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@merill/lokka','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@novu/application-generic','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@papra/webhooks','{"CWE-918"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@platejs/docx-io','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@sync-in/server','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@utcp/http','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@wonderwhy-er/desktop-commander','{"CWE-918"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','directus','{"CWE-918"}',1,'high',0.71,false,true) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','dssrf','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','fuxa-server','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','nuxt-og-image','{"CWE-918"}',1,'low',0.46,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','signalk-server','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','unleash-server','{"CWE-918"}',1,'medium',0.57,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','@fedify/fedify','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
INSERT INTO vuln_target_map(ecosystem,package,cwe_classes,advisory_count,worst_severity,credential_score,pays,company_backed) VALUES('npm','flowise','{"CWE-918"}',1,'high',0.71,false,false) ON CONFLICT (ecosystem,package) DO UPDATE SET advisory_count=EXCLUDED.advisory_count, worst_severity=EXCLUDED.worst_severity, credential_score=EXCLUDED.credential_score, cwe_classes=EXCLUDED.cwe_classes, company_backed=EXCLUDED.company_backed, updated_at=now();
